apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    service: {{ .Values.name }}
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.name }}
  namespace: diary
spec:
  ports:
  - name: http
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.port}}
  selector:
    app: {{ .Values.name }}
