version: '3'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=diary_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=diary
    ports:
      - 5432:5432
    volumes:
      - ./storage/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  idp:
    image: oryd/hydra:v1.4.5
    command: serve all --dangerous-force-http
    ports:
      - "4444:4444"
      - "4445:4445"
    depends_on:
      - idp_migrate
      - db
    environment:
      DSN: postgres://diary_user:secret@db:5432/diary?search_path=idp
      URLS_SELF_ISSUER: http://localhost:4444
      URLS_CONSENT: http://localhost:8000/consent
      URLS_LOGIN: http://localhost:3000/auth/login
      URLS_LOGOUT: http://localhost:3000/auth/logout
      OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: public,pairwise
      SECRETS_SYSTEM: youReallyNeedToChangeThis
      OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: youReallyNeedToChangeThis


  idp_migrate:
    image: oryd/hydra:v1.4.5
    command: migrate sql -e --yes
    depends_on:
      - db
    environment:
      DSN: postgres://diary_user:secret@db:5432/diary?search_path=idp
