# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

orbs:
  docker: circleci/docker@0.5.10

executors:
  diary-api:
    docker:
      - image: rasouza/php:7.2-fpm

jobs:
  build:
    executor: diary-api
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: pwd
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: diary-api
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run: ./vendor/bin/phpunit

workflows:
  test:
    jobs:
      - build
      - test:
          requires:
            - build
  deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker/publish:
          image: rasouza/$CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_TAG/v/''}
          dockerfile: .circleci/Dockerfile
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - test

