steps:

  - name: ":phpunit:"
    command:
      - sleep 2
      - vendor/bin/phpunit
    plugins:
      - docker-compose#v3.1.0:
          run: users

  - wait

  - name: ":docker:"
    branches: master
    plugins:
      - docker-compose#v3.1.0:
          push: users:rasouza/diary-users:latest

  - name: ":docker:"
    if: build.tag =~ /^v.*/
    plugins:
      - docker-compose#v3.1.0:
          push: users:rasouza/diary-users:${BUILDKITE_TAG:1:8}

  - wait

  - name: ":rocket:"
    if: build.tag =~ /^v.*/ || build.branch == "master"
    trigger: diary-users-deploy
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        IMAGE_TAG: ${BUILDKITE_TAG:1:8}
