apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o .deployment/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o .deployment/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: users
    spec:
      containers:
      - image: rasouza/diary-api-users
        name: users
        command: ["php", "artisan", "serve"]
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
