apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o .deployment/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: users
    app: users
    service: users
  name: users
  namespace: diary
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: users
status:
  loadBalancer: {}
